# Generated by Django 4.2.16 on 2024-09-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=50, unique=True, verbose_name='Codigo')),
                ('Nombres', models.CharField(max_length=50, verbose_name='Nombre')),
                ('Apellido1', models.CharField(max_length=20, verbose_name='Apellido1')),
                ('Apellido2', models.CharField(max_length=20, verbose_name='Apellido2')),
                ('Direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('Telefono', models.CharField(max_length=50, verbose_name='Telefono')),
            ],
            options={
                'verbose_name_plural': 'Datos',
            },
        ),
    ]
