# Generated by Django 4.2.16 on 2024-09-26 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bicicleta', '0001_initial'),
        ('Reparacion', '0002_alter_reparacion_costo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaReparacion', models.CharField(max_length=10)),
                ('CostoReparacion', models.CharField(max_length=5)),
                ('Observaciones', models.CharField(max_length=50)),
                ('BicicletaId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Bicicleta.bicicleta', verbose_name='Bicicleta')),
                ('ReparacionId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Reparacion.reparacion', verbose_name='Reparacion')),
            ],
        ),
    ]
