# Generated by Django 4.2.16 on 2024-09-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reparacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacion',
            name='Costo',
            field=models.CharField(max_length=5, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='DescripcionReparacion',
            field=models.CharField(max_length=50, verbose_name='Codigo'),
        ),
    ]
