# Generated by Django 4.2.16 on 2024-09-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoRepuesto', models.CharField(max_length=50, unique=True, verbose_name='Codigo')),
                ('DescripcionRepuesto', models.CharField(max_length=50, verbose_name='Codigo')),
                ('Costo', models.CharField(max_length=50, verbose_name='Codigo')),
            ],
        ),
    ]
