# Generated by Django 4.2.16 on 2024-09-26 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DetalleReparacion', '0001_initial'),
        ('Repuesto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Costo', models.CharField(max_length=5)),
                ('DetalleReparacion_Id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='DetalleReparacion.detallereparacion')),
                ('Repuesto_Id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Repuesto.repuesto')),
            ],
        ),
    ]
