# Generated by Django 4.2.16 on 2024-09-26 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoCliente', models.CharField(max_length=50, unique=True, verbose_name='Codigo')),
                ('Dato_Id', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, to='Dato.dato', verbose_name='Dato_Id')),
            ],
        ),
    ]
