# Generated by Django 4.2.16 on 2024-09-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaAlquiler', models.DateTimeField(auto_now_add=True, verbose_name='FechaAlquiler')),
                ('Descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('CodigoAlquiler', models.CharField(max_length=8, verbose_name='CodigoAlquiler')),
            ],
        ),
    ]
