# Generated by Django 4.2.16 on 2024-11-14 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cliente', '0001_initial'),
        ('Empleado', '0001_initial'),
        ('Bicicleta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaAlquiler', models.DateTimeField(auto_now_add=True, verbose_name='FechaAlquiler')),
                ('Descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('CodigoAlquiler', models.CharField(max_length=8, verbose_name='CodigoAlquiler')),
                ('Cliente_Id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Cliente.cliente', verbose_name='Cliente')),
                ('Empleado_Id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Empleado.empleado', verbose_name='Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleAlquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaAlquiler', models.DateTimeField(auto_now_add=True)),
                ('FechaDevolucion', models.DateTimeField()),
                ('FechaRealDevolucion', models.DateTimeField(blank=True, null=True)),
                ('Costo', models.CharField(max_length=5)),
                ('Cantidad', models.IntegerField()),
                ('Alquiler_Id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='DetallesAlquiler', to='Alquiler.alquiler', verbose_name='Alquiler')),
                ('Bicicleta_Id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Bicicleta.bicicleta', verbose_name='Bicicleta')),
            ],
        ),
    ]
